In [1]:
import numpy as np

X = np.array([[1, 2, 3], [4, 5, 6]])
print(X.shape)
w = np.zeros(X.shape[1])
print(w)
print(len(X))

(2, 3)
[0. 0. 0.]
2


PLA实现
	
$$ 
f_{w,b} (x) = wx + b
$$

In [26]:
import numpy as np

# wx +b
def pla(X, y):
    #初始化权重系数
    W = np.zeros(X.shape[1])
    flag = False
    while (flag == False):
        flag = True
        for index in range(len(X)):
            x = X[index]
            if np.dot(x * W, y[index])<=0:
                #修正w系数
                flag = False
                W = W + y[index] * x
    return W


print(pla(np.array([[1, 8, 19], [2, 10, 19], [3, 10, 17]]),
          np.array([[2, 0, 1], [4, 0, 0], [3, 0, 17]])
          ))


[ 2.  0. 19.]


生成数据集

In [24]:
import numpy as np

def generate_data_collect(W,start, end, size =10):
    #np.random.seed(42)
    # 随机生成 size=10个 元素,uniform为随机浮点数, randint为随机整数  [start, end) 输出样本为 size=(m,n,k), 则输出 m * n * k 个样本 10行2列
    x = np.random.randint(start, end, (size, W.shape[0]))
    # 矩阵x点乘W的符号 sign(x)函数 x>0返回1, x=0返回0  x<0返回-1
    y = np.sign(x.dot(W))
    return x,y

start = -10
# 坐标轴结束点
end = 10
# 目标权重系数
W = np.array([5, 4])
# 创建线性可分的训练数据集
X, y = generate_data_collect(W, start, end)
print(X,y)

def createLine(W, min, max , size =100):
    x0 = np.linspace(min, max, size)
    # 行列式第二行为0
    if W[1] == 0:
        x1 = np.zeros(size)
    else:
        x1 = -W[0] * x0 /W[1]
    return x0, x1    
    

[[ 4 -4]
 [ 1 -3]
 [ 4 -8]
 [ 3  6]
 [-7  7]
 [-3 -7]
 [-9 -5]
 [-1 -7]
 [ 7  1]
 [-9 -1]] [ 1 -1 -1  1 -1 -1 -1 -1  1 -1]


打印字体

In [2]:
import matplotlib.font_manager as fm

fonts = fm.findSystemFonts(fontpaths=None, fontext='ttf')
print(fonts)

['C:\\Windows\\Fonts\\segoesc.ttf', 'C:\\ProgramData\\kingsoft\\office6\\omath\\DejaVuMathTeXGyre.ttf', 'C:\\Windows\\Fonts\\cambria.ttc', 'C:\\Windows\\Fonts\\georgia.ttf', 'C:\\Windows\\Fonts\\NirmalaS.ttf', 'C:\\Windows\\Fonts\\LeelUIsl.ttf', 'C:\\Windows\\Fonts\\SitkaB.ttc', 'C:\\Windows\\Fonts\\timesi.ttf', 'C:\\Windows\\Fonts\\ntailub.ttf', 'F:\\Rational\\Common\\java\\jre\\lib\\fonts\\LucidaBrightDemiBold.ttf', 'F:\\Rational\\Common\\java\\jre\\lib\\fonts\\LucidaSansRegular.ttf', 'C:\\Windows\\Fonts\\malgun.ttf', 'C:\\Windows\\Fonts\\segmdl2.ttf', 'C:\\Windows\\Fonts\\couri.ttf', 'C:\\Windows\\Fonts\\seguisli.ttf', 'C:\\Windows\\Fonts\\seguibl.ttf', 'C:\\Windows\\Fonts\\taileb.ttf', 'C:\\Windows\\Fonts\\arialbi.ttf', 'C:\\Windows\\Fonts\\Inkfree.ttf', 'C:\\Windows\\Fonts\\holomdl2.ttf', 'C:\\Windows\\Fonts\\times.ttf', 'C:\\Windows\\Fonts\\georgiaz.ttf', 'C:\\Windows\\Fonts\\msjh.ttc', 'C:\\Windows\\Fonts\\palab.ttf', 'C:\\Windows\\Fonts\\LeelawUI.ttf', 'C:\\Windows\\Fonts\\verd